services:
  neko:
    image: m1k1o/neko:firefox
    container_name: neko
    restart: unless-stopped
    shm_size: 4gb
    ports:
      - "80:8080"
      - "52000-52100:52000-52100/udp"
    environment:
      #LIBVA_DRIVER_NAME: i915
      TZ: Europe/Berlin
      NEKO_SCREEN: 1920x1080@30
      NEKO_PASSWORD: changeMe
      NEKO_PASSWORD_ADMIN: changeMe
      NEKO_EPR: 52000-52100
      NEKO_ICELITE: 1
      NEKO_CONTROL_PROTECTION: true
      NEKO_VIDEO_CODEC: h264
      NEKO_VIDEO_BITRATE: 3500
      NEKO_AUDIO_BITRATE: 320
      NEKO_BROADCAST_URL: rtmp://rtsp_server:1935/live # stream key "live" can be changed to anything.
      NEKO_PROXY: true
      #NEKO_BROADCAST_PIPELINE: "flvmux name=mux ! rtmpsink location={url} pulsesrc device={device} ! audio/x-raw,channels=2 ! audioconvert ! queue ! queue ! queue ! voaacenc bitrate=320000 ! audio/mpeg,rate=48000 ! mux. ximagesrc display-name={display} show-pointer=false use-damage=false ! video/x-raw,framerate=30/1 ! videoconvert ! video/x-raw,framerate=30/1,format=I420 ! queue ! queue ! queue ! x264enc key-int-max=30 pass=qual quantizer=20 speed-preset=veryfast ! mux." # config for variable bitrate
      NEKO_BROADCAST_PIPELINE: "flvmux name=mux ! rtmpsink location={url} pulsesrc device={device} ! audio/x-raw,channels=2 ! audioconvert ! queue ! queue ! queue ! voaacenc bitrate=320000 ! audio/mpeg,rate=48000 ! mux. ximagesrc display-name={display} show-pointer=false use-damage=false ! video/x-raw,framerate=30/1 ! videoconvert ! video/x-raw,framerate=30/1,format=I420 ! queue ! queue ! queue ! x264enc key-int-max=30 bitrate=4000 speed-preset=veryfast ! mux." # config for fixed bitrate

  rtsp_server:
    image: bluenviron/mediamtx:latest-ffmpeg
    container_name: mediamtx
    restart: unless-stopped
    ports:
      - "8554:8554" # RTSP
      - "1935:1935" # RTMP
      - "8888:8888" # HLS
      #- "8889:8889" # WebRTC
      #- "8890:8890" # SRT
    environment:
      MTX_PROTOCOLS: tcp
      #MTX_WEBRTCADDITIONALHOSTS: mtx.yourdomain.tld # most likely not needed
      MTX_HLSALWAYSREMUX: yes
      MTX_HLSVARIANT: mpegts # do not change this for maximum compatibility
      MTX_HLSSEGMENTCOUNT: 7
      MTX_HLSSEGMENTDURATION: 1s
