services:
  neko:
    image: ghcr.io/m1k1o/neko/intel-firefox:latest
    container_name: neko
    restart: unless-stopped
    shm_size: 4gb
    cap_add:
      - SYS_ADMIN
    ports:
      - "80:8080"
      - "52000-52100:52000-52100/udp"
    environment:
      #LIBVA_DRIVER_NAME: i915
      TZ: Europe/Berlin
      NEKO_SCREEN: 1920x1080@30
      NEKO_PASSWORD: changeMe
      NEKO_PASSWORD_ADMIN: changeMe
      NEKO_EPR: 52000-52100
      NEKO_ICELITE: 1
      NEKO_CONTROL_PROTECTION: true
      NEKO_VIDEO_CODEC: h264
      NEKO_VIDEO_BITRATE: 6000
      NEKO_AUDIO_BITRATE: 320
      NEKO_BROADCAST_URL: rtsp_server
      NEKO_PROXY: true
      NEKO_BROADCAST_PIPELINE: "mpegtsmux name=mux alignment=7 ! queue max-size-time=2000000000 ! udpsink host=rtsp_server port=1234 buffer-size=2097152 ximagesrc display-name={display} show-pointer=true use-damage=false ! video/x-raw,framerate=30/1 ! queue max-size-buffers=300 leaky=downstream ! videoconvert ! video/x-raw,format=NV12 ! vaapih264enc rate-control=cbr bitrate=6144 keyframe-period=10 quality-level=2 ! h264parse config-interval=1 ! video/x-h264,stream-format=byte-stream,profile=main ! queue max-size-buffers=300 ! mux. pulsesrc device={device} ! audio/x-raw,channels=2 ! queue max-size-buffers=300 leaky=downstream ! audioconvert ! voaacenc bitrate=320000 ! audio/mpeg,rate=48000 ! aacparse ! queue max-size-buffers=300 ! mux."
    devices:
      - /dev/dri:/dev/dri

  rtsp_server:
    image: bluenviron/mediamtx:latest-ffmpeg
    restart: unless-stopped
    ports:
      - "8554:8554" # RTSP
      - "1935:1935" # RTMP
      - "8888:8888" # HLS
      #- "8889:8889" # WebRTC
      #- "8890:8890" # SRT
    environment:
      MTX_PROTOCOLS: tcp
      #MTX_WEBRTCADDITIONALHOSTS: mtx.yourdomain.tld # most likely not needed
      MTX_HLSALWAYSREMUX: yes
      MTX_HLSVARIANT: mpegts # do not change this for maximum compatibility
      MTX_HLSSEGMENTCOUNT: 7
      MTX_HLSSEGMENTDURATION: 2s
      MTX_PATHS_LIVE_SOURCE: "udp://rtsp_server:1234"
